version: '3.8'

services:
  mysql-master:
    image: bitnami/mysql:8.0
    restart: always
    env_file:
      - .env.master
    ports:
      - 3306
    volumes:
      - mysql_master_data:/bitnami/mysql

  mysql-slave:
    image: bitnami/mysql:8.0
    restart: always
    env_file:
      - .env.slave
    ports:
      - 3306:3306
    deploy:
      mode: replicated
      replicas: 4
    depends_on:
      - mysql-master


networks:
  db-network:
    external: true

volumes:
  mysql_master_data:
