steps:
- id: Install Dependencies
  name: gcr.io/cloud-builders/npm
  dir: '${_SERVICE}/'
  args: ['install']

- id: Lint
  name: gcr.io/cloud-builders/npm
  dir: '${_SERVICE}/'
  args: ['run', 'lint']


substitutions:
  _REGISTRY_URL: us.gcr.io/$PROJECT_ID
  _PROJECT: lab-16sz8D
  _FULL_PATH_IMAGE: ${_REGISTRY_URL}/${_PROJECT}/${_SERVICE}
